# Exercises

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [6]:
import numpy as np
# formula = weight / (height**2) * 730
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]

height_array = np.array(height)
weight_array = np.array(weight)

BMI = weight_array/(height_array**2) * 730
print(BMI)

[16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
 22.06222222]


### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [49]:
def randomizer(p_1, p_2, x1, x2, data_type):
    
    matrix = np.random.uniform(p_1, p_2,(x1, x2)) 
    new_type = matrix.astype(data_type)
    print(new_type)
    

randomizer(1, 37, 3, 3, np.int64)


[[ 4 12 25]
 [24 32  2]
 [35 14 33]]


### #3 - Extra: Open and load the data in the two text files that have the Boston Red Sox hitting data for the past seasons. Compare the difference in the two years by putting the data into an NDArray and running a differencial operation on it. The column to look for will be SLG.

Your output should display which year (either 2017 or 2018) was a better year based on SLG

In [50]:
import csv
import numpy as np



In [79]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

def load_data(filename, d = ','):
    data = np.genfromtxt(filename,delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24),invalid_raise=False,
                        names = FIELDS, dtype = DATATYPES)
    return data

bs2017 = load_data('files/redsox_2017_hitting.txt')
bs2018 = load_data('files/redsox_2018_hitting.txt')

bs2017_SLG = bs2017['SLG']
bs2018_SLG = bs2018['SLG']


for i in range(len((bs2018_SLG))):
    diff_SLG = bs2018_SLG[i] - bs2017_SLG[i]
    print(diff_SLG)




-0.125
-0.00999999
-0.0039999783
0.11900002
-0.048999995
0.04100001
0.0009999871
0.181
0.20000002
0.05700001
-0.104
-0.004999995
-0.14399996
0.26400003
0.048999995
0.06099999
0.04699999
-0.07799998
-0.23700002
-0.139
